[tool.black]
line-length = 88
target-version = ["py310"]

[tool.pylint.MASTER]
py-version = "3.10"
extension-pkg-allow-list = [
    "PyQt6",
    "PyQt6.QtWebEngineQuick",
    "PyQt6.QtWidgets",
]

disable = [
    "wrong-import-order",
]

[tool.pylint.format]
max-line-length = "88"